### ISSUE TITLE
Question about How to train my own dataset?

### ISSUE THREAD

**Issue by HyejinWon** [s-ankur/fairseq-gec#2]
Hi, Thanks to share your edit version fairseq-gec!
I'm looking for how to use fairseq-gec finally I got your repo!!

First my question is 'How to run this model used my data?'
I already prepare noise-src and raw-trg file.

And Should I have to make align file using align.sh?

I think just run preprocessing.sh and run train.sh isn't it?

**Comment by s-ankur** [comment]
Hello, the instructions along with notebooks will be found at https://github.com/s-ankur/hindi_grammar_correction
